---
version: "3"
services:
  datascience:
    image: gnasello/datascience-env:2024-05-16
    container_name: datascience-env
    user: root
    environment:
    - NB_UID=1234
    - NB_GID=1234
    - CHOWN_HOME=yes
    - CHOWN_HOME_OPTS=-R
    - GRANT_SUDO=yes
    ports:
      - 7777:8888