version: '3'

services:
  datascience:
    image: gnasello/datascience-env:2023-03-29
    build: .
    ports:
      - $JLPORT:$JLPORT
      - $RSPORT:7878
    volumes:
      - $HOME_RESEARCHER:/home/researcher # change the path before ":" with the volume you want to mount
    working_dir: /home/researcher
    entrypoint: bash /entrypoint.sh
    hostname: $HOST_NAME
    environment:
       - JLPORT=${JLPORT}
       - RSPORT=${RSPORT}
       - HOME_RESEARCHER=${HOME_RESEARCHER}
       - HOST_NAME=${HOST_NAME}